upstream react_app {
    server 172.21.0.3:80;
    server 172.21.0.4:80;
    server 172.21.0.5:80;
    server 172.21.0.6:80;
    server 172.21.0.7:80;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://react_app;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
